/*
 * generated by Xtext 2.41.0
 */
package org.xtext.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.dsl.PokemonRuntimeModule;
import org.xtext.dsl.PokemonStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PokemonIdeSetup extends PokemonStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PokemonRuntimeModule(), new PokemonIdeModule()));
	}
	
}
