/*
 * generated by Xtext 2.41.0
 */
package org.xtext.dsl.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.AbstractGenerator
import org.eclipse.xtext.generator.IFileSystemAccess2
import org.eclipse.xtext.generator.IGeneratorContext
import org.xtext.dsl.pokemon.Pokemon
import org.xtext.dsl.pokemon.Move
import org.xtext.dsl.pokemon.Model
import org.xtext.dsl.pokemon.Trainer

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
class PokemonGenerator extends AbstractGenerator {

	override void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
//		fsa.generateFile('greetings.txt', 'People to greet: ' + 
//			resource.allContents
//				.filter(Greeting)
//				.map[name]
//				.join(', '))
		for (pokemon : resource.allContents.toIterable.filter(Pokemon)){
			fsa.generateFile(pokemon.name + ".java", '''
				public class «pokemon.name» {
					public int hp = «pokemon.hp»;
					public int attack = «pokemon.attack»;
					public int defense = «pokemon.defense»;
					public int spatk = «pokemon.spatk»;
					public int spdef = «pokemon.spdef»;
					public int speed = «pokemon.speed»;
					public String type = «pokemon.type»;
					public int lvl = «pokemon.lvl»;
					
					public void printStats(){
						System.out.println("Health Points : " + hp);
					}
				}
			''')
		}
		for (move : resource.allContents.toIterable.filter(Move)){
			fsa.generateFile(move.name + ".java",'''
				public class «move.name» {
					public int power = «move.power»;
					public int acc = «move.acc»;
					public int pp = «move.pp»;
					public String type = «move.type»;
				}
			''')
		}
		
		val model = resource.contents.head as Model
		

		fsa.generateFile("game-summary.txt", model.compileSummary)
		

		for (p : model.pokemon) {
			fsa.generateFile("pokemon/" + p.name + ".txt", p.compilePokemon)
		}
		

		for (t : model.trainer) {
			fsa.generateFile("trainers/" + t.name + ".txt", t.compileTrainer)
		}
	}

	def compileSummary(Model model) '''
		
		
		Players:
		«FOR p : model.players»
		- «p.name» (money: «p.money»)
		  Party: «FOR poke : p.team SEPARATOR ", "»«poke.name»«ENDFOR»
		«ENDFOR»
		
		Trainers:
		«FOR t : model.trainer»
		- «t.name»
		  Party: «FOR poke : t.team SEPARATOR ", "»«poke.name»«ENDFOR»
		«ENDFOR»
		
		Pokemon:
		«FOR p : model.pokemon»
		- «p.name» | lvl «p.lvl» | type «p.type»
		«ENDFOR»
		
		Moves:
		«FOR m : model.move»
		- «m.name» | type «m.type» | power «m.power» | accuracy «m.acc» | pp «m.pp»
		«ENDFOR»
		
		Explore Sections:
		«FOR e : model.explore»
		- explore block with «e.routes.size» routes
		«FOR r : e.routes»
		  - route «r.name» with «r.events.size» events
		«ENDFOR»
		«ENDFOR»
	'''

	def compilePokemon(Pokemon p) '''
		Pokemon: «p.name»
		Wild: «IF p.isWild»yes«ELSE»no«ENDIF»
		Level: «p.lvl»
		Type: «p.type»
		
		Stats:
		- HP: «p.hp»
		- Attack: «p.attack»
		- Defense: «p.defense»
		- Sp. Atk: «p.spatk»
		- Sp. Def: «p.spdef»
		- Speed: «p.speed»
		
		Moves:
		«FOR m : p.moves»
		- «m.name»
		«ENDFOR»
	'''

	def compileTrainer(Trainer t) '''
		Trainer: «t.name»
		
		Party:
		«FOR p : t.team»
		- «p.name»
		«ENDFOR»
	'''
		
	
}
