grammar org.xtext.example.mydsl.MyDsl with org.eclipse.xtext.common.Terminals

generate myDsl "http://www.xtext.org/example/mydsl/MyDsl"

Model:
    ( players+=Player | explore+=Explore | pokemon+=Pokemon | move+=Move | trainer+=Trainer)* 
;
    
Player:
    'player' name=ID '{' 'money' money=INT 'party' '(' team+=[Pokemon] (',' team+=[Pokemon])* ')' '}'; 

Trainer:
	'trainer' name=ID '{' 'party' '(' team+=[Pokemon] (',' team+=[Pokemon])* ')' '}'
;

Pokemon:
    (isWild?='wild')?	'pokemon' name=ID '{' 
    (('hp' hp=INT) &
    ('attack' attack=INT) &
    ('defense' defense=INT) &
    ('sp.atk' spatk=INT) &
    ('sp.def' spdef=INT) &
    ('speed' speed=INT)) 
    'lvl' lvl=INT
    'type' type=STRING
    'move' '(' moves+=[Move] (',' moves+=[Move])* ')'
    '}'
    ;

Action:
    'action' name=('attack'| 'catch' |'flee') ('->' 'outcome' ':' description=STRING)?
;

Move:
	'move' name=ID 'type' type=STRING 'power' power=INT 'accuracy' acc=INT 'pp' pp=INT
;

Explore:
    'explore' '{' route+=Route+ '}'
    
;

Event:
    RandomItem | Battle | HealingCenter
;

Route:

	'route' name=ID 'event' '{' event+=Event+ '}'
;

Battle:
	WildEncounter | TrainerBattle
;

WildEncounter:
    'encounter' name=ID 'wild'  wildPokemon=[Pokemon] '{' (actions+= Action)* ('win' 'goto' winNext=[Event])? ('lose' 'goto' loseNext=[Event])? '}'
    
;

TrainerBattle:
	'battle' name=ID 'vs' opponent=[Trainer] '{' ('win' 'goto' winNext=[Event])? ('lose' 'goto' loseNext=[Event])? '}'
;

RandomItem:
    'random_item' name=ID 'found' quantity=INT description=STRING ('then' 'goto' next=[Event])?
;

HealingCenter:
	'heal' name=ID 'at' description=STRING ('then' 'goto' next=[Event])?
;
