/*
 * generated by Xtext 2.41.0
 */
package org.xtext.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PokemonStandaloneSetup extends PokemonStandaloneSetupGenerated {

	public static void doSetup() {
		new PokemonStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
