grammar org.xtext.dsl.Pokemon with org.eclipse.xtext.common.Terminals

generate pokemon "http://www.xtext.org/dsl/Pokemon"

Model:
    ( players+=Player | explore+=Explore | pokemon+=PokemonDef | move+=Move | trainer+=Trainer)* 
;
    
Player:
    'player' name=ID '{' 'money' money=INT 'party' '(' team+=PokemonInstance (',' team+=PokemonInstance)* ')' '}'; 

Trainer:
	'trainer' name=ID '{' 'party' '(' team+=PokemonInstance (',' team+=PokemonInstance)* ')' '}'
;

PokemonDef:
    (isWild?='wild')?	'pokemon' name=ID '{' 
    (('hp' hp=Exp) &
    ('attack' attack=Exp) &
    ('defense' defense=Exp) &
    ('sp.atk' spatk=Exp) &
    ('sp.def' spdef=Exp) &
    ('speed' speed=Exp)) 
    'type' type=STRING
    'move' '(' moves+=[Move] (',' moves+=[Move])* ')'
    '}'
    ;

PokemonInstance:
	species=[PokemonDef] 'lvl' level=INT
;

Exp:
	Addition
;

Addition returns Exp:
	Multiplication ({Addition.left=current} op=('+'|'-') right=Multiplication)*
;

Multiplication returns Exp:
	Primary ({Multiplication.left=current} op=('*'|'/') right=Primary)*
;

Primary returns Exp:
	NumVal | LvlRef | '(' Exp ')'
;
NumVal returns Exp:
	{NumVal} value=INT
;
LvlRef returns Exp:
	{LvlRef} 'lvl'
;

Action:
    'action' name=('attack'| 'catch' |'flee') ('->' 'outcome' ':' description=STRING)?
;

Move:
	'move' name=ID 'type' type=STRING 'power' power=INT 'accuracy' acc=INT 'pp' pp=INT
;

Explore:
    'explore' '{' routes+=Route+ '}'
;

Route:
    'route' name=ID
    (description=STRING)?
    '{'
        events+=Event*
        ('exits' '(' exits+=[Route] (',' exits+=[Route])* ')')?
    '}'
;

Event:
    WildEncounter | TrainerBattle | RandomItem | HealingCenter
;

WildEncounter:
    {WildEncounter} 'encounter' name=ID 'wild' 'pokemon' pokemon=PokemonInstance (catchable?='catchable')? '{'
        (actions+=Action)*
        ('win'  'goto' winNext=[Route])?
        ('lose' 'goto' loseNext=[Route])?
    '}'
;

TrainerBattle:
    {TrainerBattle} 'battle' name=ID 'vs' opponent=[Trainer] '{'
        ('win'  'goto' winNext=[Route])?
        ('lose' 'goto' loseNext=[Route])?
    '}'
;

RandomItem:
    {RandomItem} 'random_item' name=ID 'found' quantity=INT description=STRING
    ('then' 'goto' next=[Route])?
;

HealingCenter:
    {HealingCenter} 'heal' name=ID 'at' description=STRING
    ('then' 'goto' next=[Route])?
;
