/*
 * generated by Xtext 2.41.0
 */
package org.xtext.dsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PokemonRuntimeModule extends AbstractPokemonRuntimeModule {
}
